version: "3"
services:
  postgres-service:
    image: postgres:12
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "5000:8000"
    depends_on:
      - postgres-service
